FROM node:16 AS builder
WORKDIR /usr/src/app
COPY . .
RUN npm install --force
RUN npm run build

FROM node:16-alpine
WORKDIR /usr/src/app
USER node
COPY --from=builder /usr/src/app ./
CMD ["node", "dist/src/main"]
