export const ConfigData = {
  NODE_ENV: 'NODE_ENV',
  GRAPH_SERVER_CONNECTION_URL: 'GRAPH_SERVER_CONNECTION_URL',
  GDB_HTTP_ENDPOINT: 'GDB_HTTP_ENDPOINT',
  GRAPH_SERVER_CONNECTION_USERNAME: 'GRAPH_SERVER_CONNECTION_USERNAME',
  GRAPH_SERVER_CONNECTION_PASSWORD: 'GRAPH_SERVER_CONNECTION_PASSWORD',
  SLACK_ERR_ALARM_URL: 'SLACK_ERR_ALARM_URL',
  SENTRY_DSN: 'SENTRY_DSN',
  QA_PERIOD: 'QA_PERIOD',
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',
  AWS_S3_BUCKET_NAME: 'AWS_S3_BUCKET_NAME',
  AWS_S3_BUCKET_REGION: 'AWS_S3_BUCKET_REGION',
  AWS_S3_URL: 'AWS_S3_URL',
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  OTEL_EXPORTER_OTLP_ENDPOINT: 'OTEL_EXPORTER_OTLP_ENDPOINT',
} as const;

export type ConfigDataType = typeof ConfigData[keyof typeof ConfigData];
